[package]
name = "phonon-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "phonon"
path = "src/main.rs"

[dependencies]
# Workspace
log.workspace = true
env_logger.workspace = true
anyhow.workspace = true
tokio.workspace = true
clap.workspace = true

phonon-core = { path = "../phonon-core" }
phonon-codec = { path = "../phonon-codec" }
phonon-source = { path = "../phonon-source" }