# cargo-about config: filter out unacceptable licenses from generated report
# https://github.com/EmbarkStudios/cargo-about

[accepted-licenses]
licenses = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT OR Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "CC0-1.0",
    " MPL-2.0",
    "MPL-2.0",
]
