#!/usr/bin/env python3
"""Convert WebPlotDigitizer CSV exports to Rust `[(f32, f32); 64]` arrays.

Usage:
    python tools/wpd_csv_to_rust_arrays.py OE.csv IE.csv IE2019.csv

Each input CSV is a WebPlotDigitizer export (x=frequency_Hz, y=dB). The script
re-samples each curve onto the canonical 64-point log grid (20 Hz .. 20 kHz)
defined in `workspace/crates/calibration-engine/extraction/FREQ_64.txt` using
log-frequency linear interpolation, then prints a Rust source block ready to
paste into `harman.rs`.

Output goes to stdout. Redirect or copy-paste as needed.
"""

from __future__ import annotations

import csv
import math
import sys
from pathlib import Path

# --- canonical 64-point log grid (must match harman.rs::ie_log_freq) ---------
N_POINTS = 64
F_MIN = 20.0
F_MAX = 20_000.0


def canonical_freqs() -> list[float]:
    return [F_MIN * (F_MAX / F_MIN) ** (i / (N_POINTS - 1)) for i in range(N_POINTS)]


def read_freq_table(path: Path) -> list[float]:
    """Read FREQ_64.txt (optional — only used for cross-check)."""
    freqs = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # format: "idx\tfreq"
        parts = line.split("\t")
        if len(parts) >= 2:
            freqs.append(float(parts[1]))
    return freqs


def parse_wpd_csv(path: Path) -> list[tuple[float, float]]:
    """Parse a WebPlotDigitizer CSV export.

    Accepts both header and headerless CSV. Columns: x=Hz, y=dB.
    Skips blank / non-numeric rows.
    """
    pts: list[tuple[float, float]] = []
    with path.open(newline="") as fh:
        reader = csv.reader(fh)
        for row in reader:
            if not row or len(row) < 2:
                continue
            try:
                x = float(row[0])
                y = float(row[1])
            except ValueError:
                # header or comment line
                continue
            if x <= 0 or not math.isfinite(y):
                continue
            pts.append((x, y))
    pts.sort(key=lambda p: p[0])
    return pts


def resample_log_linear(
    pts: list[tuple[float, float]], targets: list[float]
) -> list[float]:
    """Resample (freq, db) points onto `targets` using log-freq linear interp.

    For target frequencies outside the measured range, clamp to the nearest
    endpoint (constant extrapolation).
    """
    if not pts:
        raise ValueError("no data points parsed from CSV")

    log_x = [math.log10(p[0]) for p in pts]
    ys = [p[1] for p in pts]
    out: list[float] = []

    for f in targets:
        lx = math.log10(f)
        # binary search for the bracketing segment
        lo, hi = 0, len(log_x) - 1
        if lx <= log_x[0]:
            out.append(ys[0])
            continue
        if lx >= log_x[-1]:
            out.append(ys[-1])
            continue
        while lo + 1 < hi:
            mid = (lo + hi) // 2
            if log_x[mid] <= lx:
                lo = mid
            else:
                hi = mid
        # linear interp between log_x[lo] and log_x[hi]
        t = (lx - log_x[lo]) / (log_x[hi] - log_x[lo])
        y = ys[lo] + t * (ys[hi] - ys[lo])
        out.append(y)

    return out


def format_rust_array(name: str, freqs: list[float], dbs: list[float]) -> str:
    """Format as Rust `[(f32, f32); 64]` static initializer lines."""
    lines = [f"    // {name} — digitised via WebPlotDigitizer, resampled to 64 log pts"]
    lines.append(f"    pub static {name}: [(f32, f32); 64] = [")
    for i, (f, db) in enumerate(zip(freqs, dbs)):
        # round to 1 decimal (±0.3 dB spec tolerance)
        db_r = round(db, 1)
        lines.append(f"        ({f:.4f}, {db_r:+.1f}),")
    lines.append("    ];")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2

    targets = canonical_freqs()
    # cross-check with FREQ_64.txt if present
    freq_file = Path(__file__).resolve().parent.parent / (
        "workspace/crates/calibration-engine/extraction/FREQ_64.txt"
    )
    if freq_file.exists():
        file_freqs = read_freq_table(freq_file)
        if file_freqs:
            max_err = max(abs(a - b) for a, b in zip(targets, file_freqs))
            if max_err > 0.01:
                print(
                    f"WARNING: FREQ_64.txt disagrees with canonical grid "
                    f"(max err {max_err:.4f} Hz)",
                    file=sys.stderr,
                )

    print("// ── Auto-generated by tools/wpd_csv_to_rust_arrays.py ──────────────")
    print("// Paste into harman.rs, replacing the corresponding placeholder fn.")
    print("// Source: WebPlotDigitizer 4.8 export, resampled to 64 log pts.")
    print()
    for csv_path in argv[1:]:
        path = Path(csv_path)
        if not path.exists():
            print(f"ERROR: {csv_path} not found", file=sys.stderr)
            return 1
        pts = parse_wpd_csv(path)
        if len(pts) < 8:
            print(
                f"WARNING: {csv_path} has only {len(pts)} points "
                f"(need >= 8 for meaningful interpolation)",
                file=sys.stderr,
            )
        dbs = resample_log_linear(pts, targets)
        # derive a Rust constant name from the filename
        stem = path.stem.upper().replace("-", "_").replace(" ", "_")
        if not stem.startswith("HARMAN_"):
            stem = f"HARMAN_{stem}"
        print(format_rust_array(stem, targets, dbs))
        print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
